### ISSUE TITLE
Installation unsuccessful on OS X

### ISSUE THREAD

**Issue by ghost** [evanlucas/learnyoumongo#12]
I've tried installing multiple times, both globally and locally, with and without `sudo`. The installation always hangs after these two lines of output:

```
> kerberos@0.0.12 install /usr/local/lib/node_modules/learnyoumongo/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)
```

Setup: 
- OS X 10.10.5
- zsh 5.0.8 (x86_64-apple-darwin14.3.0)
- npm 2.14.0
- node 0.12.7

**Comment by evanlucas** [comment]
I would suggest trying a couple things:
1. `npm cache clean` and then try to reinstall. You ought to install it globally. 
2. You may want to try using either node v0.10 or the latest iojs.

**Comment by ghost** [comment]
Installed iojs and problem solved! Thank you! (Btw, that was the fastest response in history)
