### ISSUE TITLE
"Find Limit" is a misleading exercise title

### ISSUE THREAD

**Issue by prashcr** [evanlucas/learnyoumongo#18]
I'm sorry if this comes off as nitpicky.

Limit has another, more common meaning in the context of MongoDB, and this could cause confusion.
I feel "Find Project" or "Find And Project" would be a clearer name for the exercise.

**Comment by evanlucas** [comment]
Feel free to open a PR :]

**Comment by evanlucas** [comment]
v3.0.0 includes this change. Thanks!
