### ISSUE TITLE
Process.argv hint for newbies

### ISSUE THREAD

**Issue by tongrhj** [evanlucas/learnyoumongo#23]
I think it's always helpful when you first require use of the process.argv method to supply arguments to say something along the lines of:

```
**HINTS**
To access the arguments you can use the process.argv array.

**Important!** The process.argv array contains not just the arguments but also the runtime (first variable) and the script file loaded (second variable)!
This means the first argument is stored at the third position:

    process.argv[2]
```

This was something I forgot when I first started on learnyoumongo, and only knew how to resolve (by printing all the process.argv) because I'd done another nodeschool workshopper some time ago.

_This was cribbed from the tower of babel nodeschool._

**Comment by evanlucas** [comment]
I would be more than happy to accept a pull request adding this

**Comment by evanlucas** [comment]
Closed by https://github.com/evanlucas/learnyoumongo/pull/25
