### ISSUE TITLE
theres no learnyoumongo database so i cant do challenges after 2nd

### ISSUE THREAD

**Issue by ta3pks** [evanlucas/learnyoumongo#26]
my first two steps are verified theres nothing missing but
theres no learnyoumongo database so i cant solve challenges after 2nd where can i get the database
im using ubuntu 15.10

**Comment by evanlucas** [comment]
The records are inserted when you verify the exercise. This is done for simple cleanup

**Comment by ta3pks** [comment]
si it doesnt work because the verify always returns empty array which does match needs

**Comment by ta3pks** [comment]
![screenshot from 2016-01-05 15-18-56](https://cloud.githubusercontent.com/assets/9097437/12115011/b35ce74e-b3bf-11e5-98a2-6497aa6265b5.png)
heres my code and always returns an empty array

**Comment by evanlucas** [comment]
hm, have you tried checking `e` to see if an error occurred?

**Comment by ta3pks** [comment]
![screenshot from 2016-01-05 15-25-23](https://cloud.githubusercontent.com/assets/9097437/12115126/90c4c85e-b3c0-11e5-8826-a6d217933248.png)
result is exact the same

**Comment by evanlucas** [comment]
What command are you using to run the file?

**Comment by ta3pks** [comment]
`learnyoumongo verify myfile.js`

**Comment by evanlucas** [comment]
And what version of node are you using? I am trying to reproduce now

**Comment by ta3pks** [comment]
4.2.3

**Comment by evanlucas** [comment]
sorry, last question (hopefully). What version of mongo are you using?

**Comment by ta3pks** [comment]
:) 2.6.10

**Comment by ta3pks** [comment]
any update ?

**Comment by maulikdarji** [comment]
i am getting following error on `learnyounode FIND` exercise:

```
[TypeError: Cannot read property 'Kerberos' of undefined]
[ { _id: 56b3648ebe8ba67e0abfa1f4, name: 'Jenny', age: 10 } ]
```

Here is my code:

``` JS
var mongo = require('mongodb').MongoClient;
var age = process.argv[2];
var url = 'mongodb://localhost:27017/learnyoumongo'

mongo.connect(url, function(err, db) {
  if (err) console.error(err);
  var parrots = db.collection('parrots')
  parrots.find({
    age: {
      $gt: +age
    }
  }).toArray(function(err, docs) {
    if (err) console.error(err);
    console.log(docs);
    db.close();
  });
});
```

`DB Version:2.6.11`

Why am i getting `Cannot read property 'Kerberos' of undefined`??

**Comment by adcoelho** [comment]
@maulikdarji do you have the mongoose module installed? It seems that module has to do with having an older version of it installed.
