### ISSUE TITLE
Getting error while setting mongodb path on windows

### ISSUE THREAD

**Issue by ghost** [evanlucas/learnyoumongo#32]
I'm jus getting started in mongodb.
While trying out do learnyoumongo connect tutorial I am trying to run this command
`mongod --port 27017 --dbpath=./data`
Here is the screenshot of the error that I am getting.
![2016-03-03 1](https://cloud.githubusercontent.com/assets/12221775/13490175/034f47ce-e151-11e5-88b4-79b0918cbaed.png)
My machine is windows 7 32 bit.
Please help.
Thanks in advance.

**Comment by evanlucas** [comment]
That appears to be an issue with mongo itself. Not really sure what is going on there. Have you searched for the specific error you are getting?

**Comment by ghost** [comment]
Yes. But no solution.
My system is 32 bit. That's why the problem appears. On 64 bit it doesn't happen.
Have you found any solution for 32 bit systems?

**Comment by JoeDoyle23** [comment]
A year late, but there is a solution for this.  The WiredTiger storage engine is the default now in MongoDB. BUT... it's not available in the 32bit Windows version.

The solution is to use the original `mmap` storage engine by adding `--storageEngine=mmapv1` to your mongod command.

`mongod --storageEngine=mmapv1 --port 27017 --dbpath=./data`

Seeing as how this is a year old, I'm going to close this out, but feel free to jump back in if this doesn't help.
