### ISSUE TITLE
learnyoumongo install error

### ISSUE THREAD

**Issue by PREMPRAKASHSINGH** [evanlucas/learnyoumongo#35]
I am getting this warning : 
npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.

**Comment by jbonigomes** [comment]
I am getting the same error here on cloud9 set up to work with node

**Comment by evanlucas** [comment]
@PREMPRAKASHSINGH I am assuming you are using npm 3 to install the dependencies. By default, npm 3 does not install peer dependencies. This is a warning and not an error though, so it should still work.

@jbonigomes There are a few issues open regarding this package not working properly on cloud9. I honestly haven't had the time to look into what's going on with that though.
