### ISSUE TITLE
Change documentation resources?

### ISSUE THREAD

**Issue by jfcisco** [evanlucas/learnyoumongo#44]
I found it easier to consult the [Node.JS Driver Documentation](http://mongodb.github.io/node-mongodb-native/) rather than the documentation on MongoDB.com, which is what learnyoumongo currently uses.

**Comment by JoeDoyle23** [comment]
I think this makes total sense. In the PR, references to syntax now point to the Node.js driver, but I left the links which point to general MongoDB concepts for some topics.
