### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by evanlucas** [evanlucas/learnyoumongo#46]
Anyone interested in helping maintain this project? Unfortunately, I don't have the time to dedicate to it :]

**Comment by JoeDoyle23** [comment]
I'm willing to continue to help maintain this project. I think the only thing I don't have access to is publish rights on npm.

**Comment by evanlucas** [comment]
@JoeDoyle23 what is your npm username?

**Comment by JoeDoyle23** [comment]
joedoyle23

**Comment by evanlucas** [comment]
@JoeDoyle23 added publish rights. Thanks!
