### ISSUE TITLE
Add 'run' feature?

### ISSUE THREAD

**Issue by SaintPeter** [evanlucas/learnyoumongo#7]
Some of the automated workshops I've used  (like https://github.com/azat-co/expressworks) have a feature where you can "run" rather than "verify".  This can be helpful in producing and debugging code.  It would be especially helpful for this workshop since so much of the code is dependent on database state.

Here are the instructions from Expressworks:
 » To print these instructions again, run: expressworks print
 » To execute your program in a test environment, run: expressworks run program.js
 » To verify your program, run: expressworks verify program.js
 » For help run: expressworks help

**Comment by SaintPeter** [comment]
Correction:
It looks like you have a 'run' feature.
Please add it to the possibilities as part of the help.

**Comment by evanlucas** [comment]
Fixed in 4d2be3d9a9dea90de0d5c3ae0aad9b9b4dd97807. Published in v1.1.9

Thanks!
